2024-10-23 21:30:12 [WRN] [DotNetCore.CAP.Internal.ConsumerRegister] [12540] [48] - RabbitMQ consumer cancelled. --> amq.ctag-xDK6PK9WyJs-CPUZvpChhw
2024-10-23 21:30:12 [WRN] [DotNetCore.CAP.Internal.ConsumerRegister] [12540] [48] - RabbitMQ consumer shutdown. --> Unexpected Exception: Unable to read data from the transport connection: 远程主机强迫关闭了一个现有的连接。.
2024-10-23 21:30:12 [WRN] [DotNetCore.CAP.Internal.ConsumerRegister] [12540] [48] - RabbitMQ consumer cancelled. --> amq.ctag-OdCOx9gXf7S5Pfffnc4lLQ
2024-10-23 21:30:13 [WRN] [DotNetCore.CAP.Internal.ConsumerRegister] [12540] [48] - RabbitMQ consumer shutdown. --> Unexpected Exception: Unable to read data from the transport connection: 远程主机强迫关闭了一个现有的连接。.
2024-10-23 21:40:15 [WRN] [DotNetCore.CAP.Internal.ConsumerRegister] [12540] [48] - RabbitMQ consumer cancelled. --> amq.ctag-xDK6PK9WyJs-CPUZvpChhw
2024-10-23 21:40:16 [WRN] [DotNetCore.CAP.Internal.ConsumerRegister] [12540] [48] - RabbitMQ consumer shutdown. --> Unexpected Exception: Unable to read data from the transport connection: 远程主机强迫关闭了一个现有的连接。.
2024-10-23 21:40:17 [WRN] [DotNetCore.CAP.Internal.ConsumerRegister] [12540] [48] - RabbitMQ consumer cancelled. --> amq.ctag-OdCOx9gXf7S5Pfffnc4lLQ
2024-10-23 21:40:19 [WRN] [DotNetCore.CAP.Internal.ConsumerRegister] [12540] [48] - RabbitMQ consumer shutdown. --> Unexpected Exception: Unable to read data from the transport connection: 远程主机强迫关闭了一个现有的连接。.
2024-10-23 22:28:25 [WRN] [DotNetCore.CAP.Internal.ConsumerRegister] [12540] [10] - RabbitMQ consumer cancelled. --> amq.ctag-xDK6PK9WyJs-CPUZvpChhw
2024-10-23 22:28:31 [WRN] [DotNetCore.CAP.Internal.ConsumerRegister] [12540] [10] - RabbitMQ consumer shutdown. --> Unexpected Exception: Unable to read data from the transport connection: 远程主机强迫关闭了一个现有的连接。.
2024-10-23 22:28:32 [WRN] [DotNetCore.CAP.Internal.ConsumerRegister] [12540] [10] - RabbitMQ consumer cancelled. --> amq.ctag-OdCOx9gXf7S5Pfffnc4lLQ
2024-10-23 22:28:33 [WRN] [DotNetCore.CAP.Internal.ConsumerRegister] [12540] [10] - RabbitMQ consumer shutdown. --> Unexpected Exception: Unable to read data from the transport connection: 远程主机强迫关闭了一个现有的连接。.
